# Generated by Django 3.0.7 on 2020-07-11 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models
import mapbox_location_field.spatial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=1500)),
                ('Phone', models.CharField(max_length=12)),
                ('location', mapbox_location_field.spatial.models.SpatialLocationField(map_attrs={'center': [-74.006, 40.7128], 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'blue', 'navigation_buttons': True, 'rotate': False, 'style': 'mapbox://styles/alexbohlin/ckbv8apzk17m61jny7fiyyhro', 'track_location_button': True, 'zoom': 13}, srid=4326)),
                ('address', mapbox_location_field.models.AddressAutoHiddenField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
