# Generated by Django 3.0.7 on 2020-08-07 18:08

from django.db import migrations
import mapbox_location_field.spatial.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=mapbox_location_field.spatial.models.SpatialLocationField(map_attrs={'center': [-74.006, 40.7128], 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'blue', 'navigation_buttons': True, 'rotate': False, 'style': 'mapbox://styles/alexbohlin/ckcmcftt01hxi1kpgmiv520n0', 'track_location_button': True, 'zoom': 13}, srid=4326),
        ),
    ]
