# Generated by Django 3.0.7 on 2020-08-07 19:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_auto_20200807_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
